# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-21 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.IntegerField(choices=[(1, 'pressure'), (2, 'outtemp'), (3, 'outhumidity'), (4, 'windspeed'), (5, 'winddir'), (6, 'rain'), (7, 'dewpoint'), (8, 'windchill'), (9, 'et'), (10, 'radiation'), (11, 'radiation_total'), (12, 'txbatterystatus'), (13, 'intempbatterystatus')], db_column='variable', default=0)),
                ('control_var', models.IntegerField(choices=[(0, ' '), (1, 'NONE'), (2, 'MINIMO'), (3, 'MAXIMO')], db_column='control_var', default=0)),
                ('valor', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_column='dateTime')),
                ('usunits', models.IntegerField(db_column='usUnits')),
                ('interval', models.IntegerField()),
                ('barometer', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('altimeter', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('intemp', models.DecimalField(blank=True, db_column='inTemp', decimal_places=1, max_digits=3, null=True)),
                ('outtemp', models.DecimalField(blank=True, db_column='outTemp', decimal_places=1, max_digits=3, null=True)),
                ('inhumidity', models.DecimalField(blank=True, db_column='inHumidity', decimal_places=1, max_digits=4, null=True)),
                ('outhumidity', models.DecimalField(blank=True, db_column='outHumidity', decimal_places=1, max_digits=4, null=True)),
                ('windspeed', models.DecimalField(blank=True, db_column='windSpeed', decimal_places=1, max_digits=5, null=True)),
                ('winddir', models.DecimalField(blank=True, db_column='windDir', decimal_places=1, max_digits=4, null=True)),
                ('windgust', models.DecimalField(blank=True, db_column='windGust', decimal_places=1, max_digits=4, null=True)),
                ('windgustdir', models.DecimalField(blank=True, db_column='windGustDir', decimal_places=1, max_digits=5, null=True)),
                ('rainrate', models.DecimalField(blank=True, db_column='rainRate', decimal_places=1, max_digits=6, null=True)),
                ('rain', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('dewpoint', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('windchill', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('heatindex', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('et', models.DecimalField(blank=True, db_column='ET', decimal_places=1, max_digits=6, null=True)),
                ('radiation', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('radiation_total', models.DecimalField(blank=True, db_column='radiation_total', decimal_places=1, max_digits=6, null=True)),
                ('uv', models.DecimalField(blank=True, db_column='UV', decimal_places=1, max_digits=6, null=True)),
                ('extratemp1', models.DecimalField(blank=True, db_column='extraTemp1', decimal_places=1, default=0, max_digits=3, null=True)),
                ('extratemp2', models.DecimalField(blank=True, db_column='extraTemp2', decimal_places=1, default=0, max_digits=3, null=True)),
                ('extratemp3', models.FloatField(blank=True, db_column='extraTemp3', default=0, null=True)),
                ('soiltemp1', models.FloatField(blank=True, db_column='soilTemp1', default=0, null=True)),
                ('soiltemp2', models.FloatField(blank=True, db_column='soilTemp2', default=0, null=True)),
                ('soiltemp3', models.FloatField(blank=True, db_column='soilTemp3', default=0, null=True)),
                ('soiltemp4', models.FloatField(blank=True, db_column='soilTemp4', default=0, null=True)),
                ('leaftemp1', models.FloatField(blank=True, db_column='leafTemp1', default=0, null=True)),
                ('leaftemp2', models.FloatField(blank=True, db_column='leafTemp2', default=0, null=True)),
                ('extrahumid1', models.FloatField(blank=True, db_column='extraHumid1', default=0, null=True)),
                ('extrahumid2', models.FloatField(blank=True, db_column='extraHumid2', default=0, null=True)),
                ('soilmoist1', models.FloatField(blank=True, db_column='soilMoist1', default=0, null=True)),
                ('soilmoist2', models.FloatField(blank=True, db_column='soilMoist2', default=0, null=True)),
                ('soilmoist3', models.FloatField(blank=True, db_column='soilMoist3', default=0, null=True)),
                ('soilmoist4', models.FloatField(blank=True, db_column='soilMoist4', default=0, null=True)),
                ('leafwet1', models.FloatField(blank=True, db_column='leafWet1', default=0, null=True)),
                ('leafwet2', models.FloatField(blank=True, db_column='leafWet2', default=0, null=True)),
                ('rxcheckpercent', models.FloatField(blank=True, db_column='rxCheckPercent', default=0, null=True)),
                ('txbatterystatus', models.FloatField(blank=True, db_column='txBatteryStatus', default=0, null=True)),
                ('consbatteryvoltage', models.FloatField(blank=True, db_column='consBatteryVoltage', default=0, null=True)),
                ('hail', models.FloatField(blank=True, default=0, null=True)),
                ('hailrate', models.FloatField(blank=True, db_column='hailRate', default=0, null=True)),
                ('heatingtemp', models.FloatField(blank=True, db_column='heatingTemp', default=0, null=True)),
                ('heatingvoltage', models.FloatField(blank=True, db_column='heatingVoltage', default=0, null=True)),
                ('supplyvoltage', models.FloatField(blank=True, db_column='supplyVoltage', default=0, null=True)),
                ('referencevoltage', models.FloatField(blank=True, db_column='referenceVoltage', default=0, null=True)),
                ('windbatterystatus', models.FloatField(blank=True, db_column='windBatteryStatus', default=0, null=True)),
                ('rainbatterystatus', models.FloatField(blank=True, db_column='rainBatteryStatus', default=0, null=True)),
                ('outtempbatterystatus', models.FloatField(blank=True, db_column='outTempBatteryStatus', default=0, null=True)),
                ('intempbatterystatus', models.FloatField(blank=True, db_column='inTempBatteryStatus', default=0, null=True)),
                ('consistente', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['datetime'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path_db', models.CharField(max_length=255)),
                ('date_installation', models.DateField(db_column='date')),
                ('time_installation', models.TimeField(db_column='hora', null=True)),
                ('departamento', models.IntegerField(choices=[(1, 'Concepcion'), (2, 'San Pedro'), (3, 'Coridillera'), (4, 'Guaira'), (5, 'Caaguazu'), (6, 'Caazapa'), (7, 'Itapua'), (8, 'Misiones'), (9, 'Paraguari'), (10, 'Alto Parana'), (11, 'Central'), (12, 'Neembucu'), (13, 'Amambay'), (14, 'Canindeyu'), (15, 'Presidente Hayes'), (16, 'Alto Paraguay'), (17, 'Boqueron')], default=0)),
                ('lat', models.FloatField()),
                ('lg', models.FloatField()),
                ('elevation', models.FloatField()),
                ('obs', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_variables.TypeStation'),
        ),
        migrations.AddField(
            model_name='record',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_variables.Station'),
        ),
    ]
